<a href="https://colab.research.google.com/github/cbonnin88/SoundStream/blob/main/Data_Cleaning_SoundStream.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import polars as pl
import gdown as gd

In [2]:
url = 'https://drive.google.com/uc?id=1w7f_WAqF4PSL1c7gwS2_eM1nuTYl2JgD'
gd.download(url,'user_behavior_raw.csv',quiet=True)

'user_behavior_raw.csv'

In [3]:
df_soundstream_raw = pl.read_csv('user_behavior_raw.csv')

In [4]:
display(df_soundstream_raw.head(5))

shape: (5, 18)
┌─────────┬───────────┬─────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ user_id ┆ country   ┆ age ┆ signup_date ┆ … ┆ desired_fut ┆ primary_de ┆ playlists_ ┆ avg_skips_ │
│ ---     ┆ ---       ┆ --- ┆ ---         ┆   ┆ ure_feature ┆ vice       ┆ created    ┆ per_day    │
│ i64     ┆ str       ┆ i64 ┆ str         ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│         ┆           ┆     ┆             ┆   ┆ str         ┆ str        ┆ i64        ┆ i64        │
╞═════════╪═══════════╪═════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 1       ┆ France    ┆ 25  ┆ 2021-08-19  ┆ … ┆ Concert     ┆ Tablet     ┆ 7          ┆ 8          │
│         ┆           ┆     ┆             ┆   ┆ Alerts      ┆            ┆            ┆            │
│ 2       ┆ Indonesia ┆ 20  ┆ 2022-06-06  ┆ … ┆ Lyrics      ┆ Mobile     ┆ 7          ┆ 6          │
│         ┆           ┆     ┆             ┆   ┆ Translation ┆            ┆            ┆            │
│ 3       ┆ Italy     ┆ 53  ┆ 2024-01-04  ┆ … ┆ Better AI   ┆ Desktop    ┆ 6          ┆ 5          │
│         ┆           ┆     ┆             ┆   ┆ Recommendat ┆            ┆            ┆            │
│         ┆           ┆     ┆             ┆   ┆ ions        ┆            ┆            ┆            │
│ 4       ┆ Italy     ┆ 48  ┆ 2018-08-26  ┆ … ┆ Social      ┆ Smart      ┆ 11         ┆ 8          │
│         ┆           ┆     ┆             ┆   ┆ Listening   ┆ Speaker    ┆            ┆            │
│ 5       ┆ Australia ┆ 18  ┆ 2020-05-29  ┆ … ┆ Lyrics      ┆ Tablet     ┆ 10         ┆ 11         │
│         ┆           ┆     ┆             ┆   ┆ Translation ┆            ┆            ┆            │
└─────────┴───────────┴─────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘

In [5]:
df_soundstream_raw.describe()

shape: (9, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ user_id   ┆ country   ┆ age       ┆ … ┆ desired_f ┆ primary_d ┆ playlists ┆ avg_skip │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ uture_fea ┆ evice     ┆ _created  ┆ s_per_da │
│ str       ┆ f64       ┆ str       ┆ f64       ┆   ┆ ture      ┆ ---       ┆ ---       ┆ y        │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ str       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 50000.0   ┆ 50000     ┆ 50000.0   ┆ … ┆ 50000     ┆ 50000     ┆ 50000.0   ┆ 50000.0  │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0.0       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 25000.5   ┆ null      ┆ 38.01028  ┆ … ┆ null      ┆ null      ┆ 8.00268   ┆ 10.02592 │
│ std       ┆ 14433.901 ┆ null      ┆ 12.984989 ┆ … ┆ null      ┆ null      ┆ 2.831571  ┆ 3.165579 │
│           ┆ 067       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 1.0       ┆ Australia ┆ 16.0      ┆ … ┆ Better AI ┆ Car       ┆ 0.0       ┆ 1.0      │
│           ┆           ┆           ┆           ┆   ┆ Recommend ┆ System    ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ations    ┆           ┆           ┆          │
│ 25%       ┆ 12501.0   ┆ null      ┆ 27.0      ┆ … ┆ null      ┆ null      ┆ 6.0       ┆ 8.0      │
│ 50%       ┆ 25001.0   ┆ null      ┆ 38.0      ┆ … ┆ null      ┆ null      ┆ 8.0       ┆ 10.0     │
│ 75%       ┆ 37500.0   ┆ null      ┆ 49.0      ┆ … ┆ null      ┆ null      ┆ 10.0      ┆ 12.0     │
│ max       ┆ 50000.0   ┆ USA       ┆ 60.0      ┆ … ┆ Social    ┆ Tablet    ┆ 23.0      ┆ 25.0     │
│           ┆           ┆           ┆           ┆   ┆ Listening ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
df_soundstream_raw.columns

['user_id',
 'country',
 'age',
 'signup_date',
 'subscription_type',
 'subscription_status',
 'months_inactive',
 'inactive_3_months_flag',
 'ad_interaction',
 'ad_conversion_to_subscription',
 'music_suggestion_rating_1_to_5',
 'avg_listening_hours_per_week',
 'favorite_genre',
 'most_liked_feature',
 'desired_future_feature',
 'primary_device',
 'playlists_created',
 'avg_skips_per_day']

In [7]:
print(f'Number of rows inside dataframe: {df_soundstream_raw.shape[0]}')
print(f'Number of columns inside dataframe: {df_soundstream_raw.shape[1]}')

Number of rows inside dataframe: 50000
Number of columns inside dataframe: 18

# **Phase 1: Data Cleaning**

In [8]:
# 1. Converting signup_date to datetime objects
# 2. Ensuring categorical columns are handled correctly

df_soundstream = df_soundstream_raw.with_columns([
    pl.col('signup_date').str.to_date('%Y-%m-%d'),
    pl.col('subscription_status').cast(pl.Categorical),
    pl.col('primary_device').cast(pl.Categorical)
])

In [17]:
# 3. Checking for any missing values
print('Missing Values per Column:')
display(df_soundstream.null_count())

Missing Values per Column:

shape: (1, 18)
┌─────────┬─────────┬─────┬─────────────┬───┬─────────────┬─────────────┬─────────────┬────────────┐
│ user_id ┆ country ┆ age ┆ signup_date ┆ … ┆ desired_fut ┆ primary_dev ┆ playlists_c ┆ avg_skips_ │
│ ---     ┆ ---     ┆ --- ┆ ---         ┆   ┆ ure_feature ┆ ice         ┆ reated      ┆ per_day    │
│ u32     ┆ u32     ┆ u32 ┆ u32         ┆   ┆ ---         ┆ ---         ┆ ---         ┆ ---        │
│         ┆         ┆     ┆             ┆   ┆ u32         ┆ u32         ┆ u32         ┆ u32        │
╞═════════╪═════════╪═════╪═════════════╪═══╪═════════════╪═════════════╪═════════════╪════════════╡
│ 0       ┆ 0       ┆ 0   ┆ 0           ┆ … ┆ 0           ┆ 0           ┆ 0           ┆ 0          │
└─────────┴─────────┴─────┴─────────────┴───┴─────────────┴─────────────┴─────────────┴────────────┘

In [15]:
df_soundstream.write_csv('soundstream_user_behavior_claned.csv')

In [16]:
display(df_soundstream.head())

shape: (5, 18)
┌─────────┬───────────┬─────┬─────────────┬───┬─────────────┬────────────┬────────────┬────────────┐
│ user_id ┆ country   ┆ age ┆ signup_date ┆ … ┆ desired_fut ┆ primary_de ┆ playlists_ ┆ avg_skips_ │
│ ---     ┆ ---       ┆ --- ┆ ---         ┆   ┆ ure_feature ┆ vice       ┆ created    ┆ per_day    │
│ i64     ┆ str       ┆ i64 ┆ date        ┆   ┆ ---         ┆ ---        ┆ ---        ┆ ---        │
│         ┆           ┆     ┆             ┆   ┆ str         ┆ cat        ┆ i64        ┆ i64        │
╞═════════╪═══════════╪═════╪═════════════╪═══╪═════════════╪════════════╪════════════╪════════════╡
│ 1       ┆ France    ┆ 25  ┆ 2021-08-19  ┆ … ┆ Concert     ┆ Tablet     ┆ 7          ┆ 8          │
│         ┆           ┆     ┆             ┆   ┆ Alerts      ┆            ┆            ┆            │
│ 2       ┆ Indonesia ┆ 20  ┆ 2022-06-06  ┆ … ┆ Lyrics      ┆ Mobile     ┆ 7          ┆ 6          │
│         ┆           ┆     ┆             ┆   ┆ Translation ┆            ┆            ┆            │
│ 3       ┆ Italy     ┆ 53  ┆ 2024-01-04  ┆ … ┆ Better AI   ┆ Desktop    ┆ 6          ┆ 5          │
│         ┆           ┆     ┆             ┆   ┆ Recommendat ┆            ┆            ┆            │
│         ┆           ┆     ┆             ┆   ┆ ions        ┆            ┆            ┆            │
│ 4       ┆ Italy     ┆ 48  ┆ 2018-08-26  ┆ … ┆ Social      ┆ Smart      ┆ 11         ┆ 8          │
│         ┆           ┆     ┆             ┆   ┆ Listening   ┆ Speaker    ┆            ┆            │
│ 5       ┆ Australia ┆ 18  ┆ 2020-05-29  ┆ … ┆ Lyrics      ┆ Tablet     ┆ 10         ┆ 11         │
│         ┆           ┆     ┆             ┆   ┆ Translation ┆            ┆            ┆            │
└─────────┴───────────┴─────┴─────────────┴───┴─────────────┴────────────┴────────────┴────────────┘